---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ttrssk8s.c.mydomain.org
    http:
      paths:
      - path: /
        backend:
          serviceName: ttrssk8s-service
          servicePort: 80

